### ISSUE TITLE
IllegalArgumentException when building a project with SDK dependency

### ISSUE THREAD

**Issue by aednlaxer** [Veriff/veriff-sample-android#1]
When building a project, an `IllegalArgumentException` exception is thrown: 
```java
Caused by: java.lang.IllegalArgumentException: Duplicate symbol in table with resource type 'string' and symbol name 'try_again'
	at com.android.ide.common.symbols.SymbolTable$Builder.add(SymbolTable.kt:204)
	at com.android.ide.common.symbols.SymbolIo$SymbolLineReader.readLines(SymbolIo.java:333)
	at com.android.ide.common.symbols.SymbolIo.read(SymbolIo.java:160)
	at com.android.ide.common.symbols.SymbolIo.readFromAapt(SymbolIo.java:110)
	at com.android.builder.core.AndroidBuilder.processResources(AndroidBuilder.java:859)
	at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.invokeAaptForSplit(LinkApplicationAndroidResourcesTask.java:512)
	at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.doFullTaskAction(LinkApplicationAndroidResourcesTask.java:257)
```

Veriff SDK has this string resource: 
```xml
<string name="try.again">Try again</string>
```
This Id can be referenced from code as `try_again` but our app module has a resource called `try_again` already (underscore separated). That's why compilation fails. Renaming app resource to something else fixes the error. My suggestion is to add a prefix to this and other Veriff resources to avoid this kind of compilation errors in future. Resource names may look like `veriff.try.again`.

Environment: SDK 1.6.8 from Maven, Android Studio 3.3.1.

**Comment by MarkKerner** [comment]
Will be fixed in Veriff SDK 2.0
